"""Shared test fixtures: a synthetic playbook and a client wired to it."""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from studio.adapters.inbound.http.app import create_app
from studio.adapters.inbound.http.dependencies import get_container
from studio.container import Container
from studio.domain.model.validation_report import ValidationReport

_REF_ALPHA = """---
domain: language
---

# REF: Alpha

> Alpha conventions.

---

## 1. Rules

Always be Alpha. See `REF-Beta.md` for the counterpart.

## 2. Skills that instantiate this REF

Generated by `scripts/sync_backlinks.py` from skill frontmatter; do not edit by hand.

Skills whose frontmatter `refs:` includes `REF-Alpha`:

- `do-alpha` - Do the alpha thing.
"""

_REF_BETA = """---
domain: practice
---

# REF: Beta

> Beta practices.

---

## 1. Guidance

Beta guidance body.
"""

_PLAYBOOK = """# AI Playbook

Route by task: `REF-Alpha.md` and `REF-Beta.md`.

## Task Routing - load only what you need

| Task | Read These REFs |
| ---- | --------------- |
| Alpha work | `REF-Alpha.md` |

## Top Violations - Check EVERY Change

1. **Do not duplicate.**
2. **No em-dashes.**
"""

_SKILL = """---
name: do-alpha
description: Do the alpha thing. Extra sentence.
refs:
  - REF-Alpha
---

# Do alpha
"""

_INTENT = """INT-001:
  version: 1.0.0
  status: active
  statement: "Alpha MUST hold."
  rationale: "Because tests."
  test:
    scope: unit
    component: Alpha
    type: invariant
  criticality: high
"""


class StubValidator:
    """Deterministic PlaybookValidator for gated-edit tests."""

    def __init__(self, ok: bool) -> None:
        self._ok = ok
        self.calls = 0

    def validate(self) -> ValidationReport:
        self.calls += 1
        return ValidationReport(
            tests_passed=self._ok,
            links_ok=self._ok,
            tests_output="stub tests",
            links_output="stub links",
        )


# Stand-ins for the playbook's bootstrap-ref / bootstrap-skill scaffolders.
# They replicate the CLI contract (args, exit code 2 on rejection, files
# written) so the studio's orchestration is tested against the contract.
_BOOTSTRAP_REF = '''
import argparse, sys
from pathlib import Path
ap = argparse.ArgumentParser()
for f in ("--name", "--domain", "--title", "--summary"):
    ap.add_argument(f, required=True)
ap.add_argument("--playbook-root", type=Path, required=True)
a = ap.parse_args()
p = a.playbook_root / f"{a.name}.md"
if p.exists():
    sys.exit(2)
p.write_text(
    f"---\\ndomain: {a.domain}\\n---\\n\\n# REF: {a.title}\\n\\n> {a.summary}\\n\\n---\\n\\n"
    f"## 1. Scope\\n\\nState the first rule set for this REF here.\\n",
    encoding="utf-8",
)
'''

_BOOTSTRAP_SKILL = '''
import argparse, json, sys
from pathlib import Path
ap = argparse.ArgumentParser()
for f in ("--name", "--description"):
    ap.add_argument(f, required=True)
ap.add_argument("--refs", default="")
ap.add_argument("--playbook-root", type=Path, required=True)
a = ap.parse_args()
refs = [r for r in a.refs.split(",") if r]
for r in refs:
    if not (a.playbook_root / f"{r}.md").is_file():
        sys.exit(2)
d = a.playbook_root / "skills" / a.name
if d.exists():
    sys.exit(2)
d.mkdir(parents=True)
refs_block = "refs:\\n" + "".join(f"  - {r}\\n" for r in refs) if refs else "refs: []\\n"
(d / "SKILL.md").write_text(
    f"---\\nname: {a.name}\\ndescription: {json.dumps(a.description)}\\n{refs_block}---\\n\\n"
    f"# {a.name}\\n\\nBody.\\n",
    encoding="utf-8",
)
pb = a.playbook_root / "AI-PLAYBOOK.md"
raw = pb.read_text(encoding="utf-8")
pb.write_text(
    raw.rstrip("\\n")
    + f"\\n\\n## Available Skills (invocable)\\n\\n| Skill | What it does | Master | Refs |\\n"
    + f"|---|---|---|---|\\n| `{a.name}` | {a.description} | `skills/{a.name}/SKILL.md` | - |\\n",
    encoding="utf-8",
) if "## Available Skills" not in raw else pb.write_text(
    raw.rstrip("\\n") + f"\\n| `{a.name}` | {a.description} | `skills/{a.name}/SKILL.md` | - |\\n",
    encoding="utf-8",
)
'''


@pytest.fixture
def playbook_root(tmp_path: Path) -> Path:
    (tmp_path / "REF-Alpha.md").write_text(_REF_ALPHA, encoding="utf-8")
    (tmp_path / "REF-Beta.md").write_text(_REF_BETA, encoding="utf-8")
    (tmp_path / "AI-PLAYBOOK.md").write_text(_PLAYBOOK, encoding="utf-8")
    (tmp_path / "intent.yaml").write_text(_INTENT, encoding="utf-8")
    skill_dir = tmp_path / "skills" / "do-alpha"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text(_SKILL, encoding="utf-8")
    for name, script in (("bootstrap-ref", _BOOTSTRAP_REF), ("bootstrap-skill", _BOOTSTRAP_SKILL)):
        d = tmp_path / "skills" / name
        d.mkdir(parents=True)
        (d / "bootstrap.py").write_text(script, encoding="utf-8")
    return tmp_path


@pytest.fixture
def passing_validator() -> StubValidator:
    return StubValidator(ok=True)


@pytest.fixture
def client(playbook_root: Path, passing_validator: StubValidator) -> TestClient:
    """TestClient against the synthetic playbook with a passing validator."""
    app = create_app()
    container = Container(
        playbook_root=playbook_root,
        validator=passing_validator,
        runtime_skills_dir=playbook_root / "_runtime",
    )
    app.dependency_overrides[get_container] = lambda: container
    return TestClient(app)


@pytest.fixture
def failing_client(playbook_root: Path) -> TestClient:
    """TestClient whose validator rejects every edit."""
    app = create_app()
    container = Container(
        playbook_root=playbook_root,
        validator=StubValidator(ok=False),
        runtime_skills_dir=playbook_root / "_runtime",
    )
    app.dependency_overrides[get_container] = lambda: container
    return TestClient(app)
