"""Shared test fixtures: a synthetic playbook and a client wired to it."""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from studio.adapters.inbound.http.app import create_app
from studio.adapters.inbound.http.dependencies import get_container
from studio.container import Container
from studio.domain.model.validation_report import ValidationReport

_REF_ALPHA = """---
domain: language
---

# REF: Alpha

> Alpha conventions.

---

## 1. Rules

Always be Alpha. See `REF-Beta.md` for the counterpart.

## 2. Skills that instantiate this REF

Generated by `scripts/sync_backlinks.py` from skill frontmatter; do not edit by hand.

Skills whose frontmatter `refs:` includes `REF-Alpha`:

- `do-alpha` - Do the alpha thing.
"""

_REF_BETA = """---
domain: practice
---

# REF: Beta

> Beta practices.

---

## 1. Guidance

Beta guidance body.
"""

_PLAYBOOK = """# AI Playbook

Route by task: `REF-Alpha.md` and `REF-Beta.md`.

## Task Routing - load only what you need

| Task | Read These REFs |
| ---- | --------------- |
| Alpha work | `REF-Alpha.md` |

## Top Violations - Check EVERY Change

1. **Do not duplicate.**
2. **No em-dashes.**
"""

_SKILL = """---
name: do-alpha
description: Do the alpha thing. Extra sentence.
refs:
  - REF-Alpha
---

# Do alpha
"""

_INTENT = """INT-001:
  version: 1.0.0
  status: active
  statement: "Alpha MUST hold."
  rationale: "Because tests."
  test:
    scope: unit
    component: Alpha
    type: invariant
  criticality: high
"""


class StubValidator:
    """Deterministic PlaybookValidator for gated-edit tests."""

    def __init__(self, ok: bool) -> None:
        self._ok = ok
        self.calls = 0

    def validate(self) -> ValidationReport:
        self.calls += 1
        return ValidationReport(
            tests_passed=self._ok,
            links_ok=self._ok,
            tests_output="stub tests",
            links_output="stub links",
        )


@pytest.fixture
def playbook_root(tmp_path: Path) -> Path:
    (tmp_path / "REF-Alpha.md").write_text(_REF_ALPHA, encoding="utf-8")
    (tmp_path / "REF-Beta.md").write_text(_REF_BETA, encoding="utf-8")
    (tmp_path / "AI-PLAYBOOK.md").write_text(_PLAYBOOK, encoding="utf-8")
    (tmp_path / "intent.yaml").write_text(_INTENT, encoding="utf-8")
    skill_dir = tmp_path / "skills" / "do-alpha"
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text(_SKILL, encoding="utf-8")
    return tmp_path


@pytest.fixture
def passing_validator() -> StubValidator:
    return StubValidator(ok=True)


@pytest.fixture
def client(playbook_root: Path, passing_validator: StubValidator) -> TestClient:
    """TestClient against the synthetic playbook with a passing validator."""
    app = create_app()
    container = Container(playbook_root=playbook_root, validator=passing_validator)
    app.dependency_overrides[get_container] = lambda: container
    return TestClient(app)


@pytest.fixture
def failing_client(playbook_root: Path) -> TestClient:
    """TestClient whose validator rejects every edit."""
    app = create_app()
    container = Container(playbook_root=playbook_root, validator=StubValidator(ok=False))
    app.dependency_overrides[get_container] = lambda: container
    return TestClient(app)
