// Generates src/models/index.ts: friendly type aliases for each OpenAPI schema.
// Auto-run by the api:generate npm script. Never hand-edit src/models/.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const spec = JSON.parse(readFileSync(resolve(root, 'src/models/openapi.json'), 'utf8'));
const schemas = Object.keys(spec.components?.schemas ?? {}).sort();

const lines = [
    '// AUTO-GENERATED by scripts/generate-barrel.mjs. Do not edit.',
    "import type { components } from './schema';",
    '',
    "export type Schemas = components['schemas'];",
    '',
    ...schemas.map((name) => `export type ${name} = components['schemas']['${name}'];`),
    '',
];

writeFileSync(resolve(root, 'src/models/index.ts'), lines.join('\n'), 'utf8');
console.log(`Generated barrel with ${schemas.length} schema types.`);
