"""Outbound port: read and write the playbook checkout."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from studio.domain.model.intent_claim import IntentClaim
from studio.domain.model.playbook_doc import PlaybookDoc
from studio.domain.model.ref_doc import RefDoc
from studio.domain.model.reference_edge import ReferenceEdge
from studio.domain.model.skill_doc import SkillDoc

__all__ = ["PlaybookRepository"]


@runtime_checkable
class PlaybookRepository(Protocol):
    """Parses the playbook folder into domain objects and applies edits.

    Scaffolding delegates to the playbook's own bootstrap-ref / bootstrap-skill
    scripts, so the studio never owns a parallel copy of the templates.
    """

    def get_playbook(self) -> PlaybookDoc: ...

    def write_playbook_document(self, *, raw: str) -> PlaybookDoc: ...

    def list_refs(self) -> list[RefDoc]: ...

    def get_ref(self, *, name: str) -> RefDoc: ...

    def list_skills(self) -> list[SkillDoc]: ...

    def get_skill(self, *, name: str) -> SkillDoc: ...

    def list_claims(self) -> list[IntentClaim]: ...

    def list_edges(self) -> list[ReferenceEdge]: ...

    def write_ref_section(self, *, ref_name: str, number: int, body: str) -> RefDoc: ...

    def write_ref_document(self, *, ref_name: str, raw: str) -> RefDoc: ...

    def write_skill_document(self, *, name: str, raw: str) -> SkillDoc: ...

    def read_skill_file(self, *, name: str, rel_path: str) -> str: ...

    def write_skill_file(self, *, name: str, rel_path: str, content: str) -> None: ...

    def scaffold_ref(self, *, name: str, domain: str, title: str, summary: str) -> RefDoc: ...

    def scaffold_skill(self, *, name: str, description: str, refs: list[str]) -> SkillDoc: ...

    def delete_ref_document(self, *, ref_name: str) -> None: ...

    def delete_skill_document(self, *, name: str) -> None: ...
